process.env.REFERENTIEL_SIRENE_API_CONSUMER_KEY = "123456";
process.env.REFERENTIEL_SIRENE_API_CONSUMER_SECRET = "secret";
process.env.REFERENTIEL_OVH_STORAGE_URI = "http://ovh";
process.env.REFERENTIEL_API_ACCE_USERNAME = "username";
process.env.REFERENTIEL_API_ACCE_PASSWORD = "secret";
process.env.TABLEAU_DE_BORD_API_KEY = "123456789";
