const { omit } = require("lodash");
const assert = require("assert");
const { createStream } = require("../utils/testUtils");
const importCFD = require("../../src/jobs/importCFD");
const { dbCollection } = require("../../src/common/db/mongodb");

const getNFormationDiplomeCsvStream = (content) => {
  return createStream(
    content ||
      `FORMATION_DIPLOME|NIVEAU_FORMATION_DIPLOME|GROUPE_SPECIALITE|LETTRE_SPECIALITE|ANCIEN_RECME|LIBELLE_COURT|LIBELLE_STAT_33|LIBELLE_LONG_200|DATE_OUVERTURE|DATE_FERMETURE|ANCIEN_DIPLOME_1|ANCIEN_DIPLOME_2|ANCIEN_DIPLOME_3|ANCIEN_DIPLOME_4|ANCIEN_DIPLOME_5|ANCIEN_DIPLOME_6|ANCIEN_DIPLOME_7|NOUVEAU_DIPLOME_1|NOUVEAU_DIPLOME_2|NOUVEAU_DIPLOME_3|NOUVEAU_DIPLOME_4|NOUVEAU_DIPLOME_5|NOUVEAU_DIPLOME_6|NOUVEAU_DIPLOME_7|UNITE_CAPITALISABLE|DATE_PREMIERE_SESSION|DATE_DERNIERE_SESSION|DATE_ARRETE_CREATION|DATE_ARRETE_ABROGATION|DATE_ARRETE_MODIFICATION_1|DATE_ARRETE_MODIFICATION_2|DATE_ARRETE_MODIFICATION_3|DATE_ARRETE_MODIFICATION_4|DATE_ARRETE_MODIFICATION_5|DATE_ARRETE_MODIFICATION_6|DATE_ARRETE_MODIFICATION_7|DATE_ARRETE_MODIFICATION_8|DATE_ARRETE_MODIFICATION_9|DATE_ARRETE_MODIFICATION_10|COMMENTAIRE|NATURE_FORMATION_DIPLOME|GESTIONNAIRE_FORMATION_DIPLOME|DATE_INTERVENTION|NB_MEF_OUVERT|NB_MEF_FERME|ID_DOCUMENT|CITE_DOMAINE_FORMATION|DATE_SESSION_RATTRAPAGE|OBSERVATION|N_COMMENTAIRE|CITE_DOMAINE_DETAILLE|NIVEAU_QUALIFICATION_RNCP
46031099|460|310|M||DIV-4|SPEC.PLURIVAL.ECHANGES & GESTION|SPECIALIT.PLURIV.DES ECHANGES & GESTION|01/09/1996||||||||||||||||||||||||||||||||S|DEP B3|10/12/2020|1|0||999||||9999|04
`
  );
};

const getVFormationDiplomeCsvStream = (content) => {
  return createStream(
    content ||
      `FORMATION_DIPLOME|NIVEAU_FORMATION_DIPLOME|GROUPE_SPECIALITE|LETTRE_SPECIALITE|ANCIEN_RECME|LIBELLE_COURT|LIBELLE_STAT_33|LIBELLE_LONG_200|DATE_OUVERTURE|DATE_FERMETURE|UNITE_CAPITALISABLE|DATE_PREMIERE_SESSION|DATE_DERNIERE_SESSION|DATE_ARRETE_CREATION|DATE_ARRETE_ABROGATION|DATE_ARRETE_MODIFICATION_1|DATE_ARRETE_MODIFICATION_2|DATE_ARRETE_MODIFICATION_3|DATE_ARRETE_MODIFICATION_4|DATE_ARRETE_MODIFICATION_5|DATE_ARRETE_MODIFICATION_6|DATE_ARRETE_MODIFICATION_7|DATE_ARRETE_MODIFICATION_8|DATE_ARRETE_MODIFICATION_9|DATE_ARRETE_MODIFICATION_10|COMMENTAIRE|NATURE_FORMATION_DIPLOME|GESTIONNAIRE_FORMATION_DIPLOME|DATE_INTERVENTION|ID_DOCUMENT|CITE_DOMAINE_FORMATION|NIVEAU_QUALIFICATION_RNCP
25032631|250|326|M||LIC-PRO|MANAG ORG MANAG RES SYS INFO|MANAGEMENT DES ORGANISATIONS SPE MANAGEMENT DES RESEAUX ET SYSTEMES D'INFORMATION (LP PARIS 2)|01/09/2006|31/08/2019|||||||31/08/2013|||||||||Univ Paris 2  0751718K habilitation 2006 0372|1|DEPP A4|10/12/2020||481|06
`
  );
};

describe("importCFD", () => {
  it("Vérifie qu'on peut importer les formations diplomes", async () => {
    const stats = await importCFD({
      nFormationDiplomeCsvStream: getNFormationDiplomeCsvStream(),
      vFormationDiplomeCsvStream: getVFormationDiplomeCsvStream(),
    });

    const results = await dbCollection("cfd").find().toArray();
    assert.strictEqual(results.length, 2);
    assert.deepStrictEqual(omit(results[0], ["_id", "__v"]), {
      FORMATION_DIPLOME: "46031099",
      NIVEAU_FORMATION_DIPLOME: "460",
      LIBELLE_COURT: "DIV-4",
    });
    assert.deepStrictEqual(stats, {
      N_FORMATION_DIPLOME: { total: 1, created: 1, updated: 0, failed: 0 },
      V_FORMATION_DIPLOME: { total: 1, created: 1, updated: 0, failed: 0 },
    });
  });

  it("Vérifie qu'on ajoute une formation V_FORMATION_DIPLOME si pas importé depuis N_FORMATION_DIPLOME", async () => {
    const stats = await importCFD({
      nFormationDiplomeCsvStream: getNFormationDiplomeCsvStream(),
      vFormationDiplomeCsvStream:
        getVFormationDiplomeCsvStream(`FORMATION_DIPLOME|NIVEAU_FORMATION_DIPLOME|GROUPE_SPECIALITE|LETTRE_SPECIALITE|ANCIEN_RECME|LIBELLE_COURT|LIBELLE_STAT_33|LIBELLE_LONG_200|DATE_OUVERTURE|DATE_FERMETURE|UNITE_CAPITALISABLE|DATE_PREMIERE_SESSION|DATE_DERNIERE_SESSION|DATE_ARRETE_CREATION|DATE_ARRETE_ABROGATION|DATE_ARRETE_MODIFICATION_1|DATE_ARRETE_MODIFICATION_2|DATE_ARRETE_MODIFICATION_3|DATE_ARRETE_MODIFICATION_4|DATE_ARRETE_MODIFICATION_5|DATE_ARRETE_MODIFICATION_6|DATE_ARRETE_MODIFICATION_7|DATE_ARRETE_MODIFICATION_8|DATE_ARRETE_MODIFICATION_9|DATE_ARRETE_MODIFICATION_10|COMMENTAIRE|NATURE_FORMATION_DIPLOME|GESTIONNAIRE_FORMATION_DIPLOME|DATE_INTERVENTION|ID_DOCUMENT|CITE_DOMAINE_FORMATION|NIVEAU_QUALIFICATION_RNCP
46031099|250|326|M||LIC-PRO|MANAG ORG MANAG RES SYS INFO|MANAGEMENT DES ORGANISATIONS SPE MANAGEMENT DES RESEAUX ET SYSTEMES D'INFORMATION (LP PARIS 2)|01/09/2006|31/08/2019|||||||31/08/2013|||||||||Univ Paris 2  0751718K habilitation 2006 0372|1|DEPP A4|10/12/2020||481|06
`),
    });

    const results = await dbCollection("cfd").find().toArray();
    assert.strictEqual(results.length, 1);
    assert.deepStrictEqual(results[0].FORMATION_DIPLOME, "46031099");
    assert.deepStrictEqual(stats, {
      N_FORMATION_DIPLOME: { total: 1, created: 1, updated: 0, failed: 0 },
      V_FORMATION_DIPLOME: { total: 1, created: 0, updated: 0, failed: 0 },
    });
  });
});
