name: CI
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Install OpenSSL 1.1 (Required for MongoDB)
        run: |
          sudo apt update
          sudo apt install -y wget
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack (for Yarn 4)
        run: corepack enable

      - name: Run tests
        run: make ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./server/.coverage
          name: codecov-server
          verbose: true
